# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-BuzzurlAPI
version:      0.02
version_from: lib/WebService/BuzzurlAPI.pm
installdirs:  site
requires:
    Class::Accessor:               0.25
    JSON::Syck:                    0.21
    LWP::UserAgent:                2.032
    Readonly:                      1.01
    UNIVERSAL::require:            0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
